# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 3.28

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

# Allow only one "make -f Makefile2" at a time, but pass parallelism.
.NOTPARALLEL:

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Disable VCS-based implicit rules.
% : %,v

# Disable VCS-based implicit rules.
% : RCS/%

# Disable VCS-based implicit rules.
% : RCS/%,v

# Disable VCS-based implicit rules.
% : SCCS/s.%

# Disable VCS-based implicit rules.
% : s.%

.SUFFIXES: .hpux_make_needs_suffix_list

# Command-line flag to silence nested $(MAKE).
$(VERBOSE)MAKESILENT = -s

#Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E rm -f

# Escaping for special characters.
EQUALS = =

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = "/mnt/c/Users/Yegor/OneDrive/Рабочий стол/lab2"

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = "/mnt/c/Users/Yegor/OneDrive/Рабочий стол/lab2"

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target test
test:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running tests..."
	/usr/bin/ctest --force-new-ctest-process $(ARGS)
.PHONY : test

# Special rule for the target test
test/fast: test
.PHONY : test/fast

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "No interactive CMake dialog available..."
	/usr/bin/cmake -E echo No\ interactive\ CMake\ dialog\ available.
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color "--switch=$(COLOR)" --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake --regenerate-during-build -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/Yegor/OneDrive/Рабочий стол/lab2/CMakeFiles" "/mnt/c/Users/Yegor/OneDrive/Рабочий стол/lab2//CMakeFiles/progress.marks"
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start "/mnt/c/Users/Yegor/OneDrive/Рабочий стол/lab2/CMakeFiles" 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named filecore

# Build rule for target.
filecore: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 filecore
.PHONY : filecore

# fast build rule for target.
filecore/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filecore.dir/build.make CMakeFiles/filecore.dir/build
.PHONY : filecore/fast

#=============================================================================
# Target rules for targets named lab2

# Build rule for target.
lab2: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 lab2
.PHONY : lab2

# fast build rule for target.
lab2/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab2.dir/build.make CMakeFiles/lab2.dir/build
.PHONY : lab2/fast

#=============================================================================
# Target rules for targets named test_runner

# Build rule for target.
test_runner: cmake_check_build_system
	$(MAKE) $(MAKESILENT) -f CMakeFiles/Makefile2 test_runner
.PHONY : test_runner

# fast build rule for target.
test_runner/fast:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_runner.dir/build.make CMakeFiles/test_runner.dir/build
.PHONY : test_runner/fast

src/BaseFile.o: src/BaseFile.cpp.o
.PHONY : src/BaseFile.o

# target to build an object file
src/BaseFile.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filecore.dir/build.make CMakeFiles/filecore.dir/src/BaseFile.cpp.o
.PHONY : src/BaseFile.cpp.o

src/BaseFile.i: src/BaseFile.cpp.i
.PHONY : src/BaseFile.i

# target to preprocess a source file
src/BaseFile.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filecore.dir/build.make CMakeFiles/filecore.dir/src/BaseFile.cpp.i
.PHONY : src/BaseFile.cpp.i

src/BaseFile.s: src/BaseFile.cpp.s
.PHONY : src/BaseFile.s

# target to generate assembly for a file
src/BaseFile.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filecore.dir/build.make CMakeFiles/filecore.dir/src/BaseFile.cpp.s
.PHONY : src/BaseFile.cpp.s

src/My_string.o: src/My_string.cpp.o
.PHONY : src/My_string.o

# target to build an object file
src/My_string.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filecore.dir/build.make CMakeFiles/filecore.dir/src/My_string.cpp.o
.PHONY : src/My_string.cpp.o

src/My_string.i: src/My_string.cpp.i
.PHONY : src/My_string.i

# target to preprocess a source file
src/My_string.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filecore.dir/build.make CMakeFiles/filecore.dir/src/My_string.cpp.i
.PHONY : src/My_string.cpp.i

src/My_string.s: src/My_string.cpp.s
.PHONY : src/My_string.s

# target to generate assembly for a file
src/My_string.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/filecore.dir/build.make CMakeFiles/filecore.dir/src/My_string.cpp.s
.PHONY : src/My_string.cpp.s

src/lab2.o: src/lab2.cpp.o
.PHONY : src/lab2.o

# target to build an object file
src/lab2.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab2.dir/build.make CMakeFiles/lab2.dir/src/lab2.cpp.o
.PHONY : src/lab2.cpp.o

src/lab2.i: src/lab2.cpp.i
.PHONY : src/lab2.i

# target to preprocess a source file
src/lab2.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab2.dir/build.make CMakeFiles/lab2.dir/src/lab2.cpp.i
.PHONY : src/lab2.cpp.i

src/lab2.s: src/lab2.cpp.s
.PHONY : src/lab2.s

# target to generate assembly for a file
src/lab2.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/lab2.dir/build.make CMakeFiles/lab2.dir/src/lab2.cpp.s
.PHONY : src/lab2.cpp.s

tests/test.o: tests/test.cpp.o
.PHONY : tests/test.o

# target to build an object file
tests/test.cpp.o:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_runner.dir/build.make CMakeFiles/test_runner.dir/tests/test.cpp.o
.PHONY : tests/test.cpp.o

tests/test.i: tests/test.cpp.i
.PHONY : tests/test.i

# target to preprocess a source file
tests/test.cpp.i:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_runner.dir/build.make CMakeFiles/test_runner.dir/tests/test.cpp.i
.PHONY : tests/test.cpp.i

tests/test.s: tests/test.cpp.s
.PHONY : tests/test.s

# target to generate assembly for a file
tests/test.cpp.s:
	$(MAKE) $(MAKESILENT) -f CMakeFiles/test_runner.dir/build.make CMakeFiles/test_runner.dir/tests/test.cpp.s
.PHONY : tests/test.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... test"
	@echo "... filecore"
	@echo "... lab2"
	@echo "... test_runner"
	@echo "... src/BaseFile.o"
	@echo "... src/BaseFile.i"
	@echo "... src/BaseFile.s"
	@echo "... src/My_string.o"
	@echo "... src/My_string.i"
	@echo "... src/My_string.s"
	@echo "... src/lab2.o"
	@echo "... src/lab2.i"
	@echo "... src/lab2.s"
	@echo "... tests/test.o"
	@echo "... tests/test.i"
	@echo "... tests/test.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -S$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

